# Generated by Django 5.0.4 on 2024-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finalziar_atividade',
            field=models.DateTimeField(null=True),
        ),
    ]
